export const types = {
  SET_SIGN_IN_EMAIL: 'SET_SIGN_IN_EMAIL',
  SET_AUTH_USER: 'SET_AUTH_USER',
  RESET_AUTH_USER: 'RESET_AUTH_USER',
  SET_DEFAULT_USER_NAME: 'SET_DEFAULT_USER_NAME',
  SET_PROFILE: 'SET_PROFILE',
};
